# Generated by Django 4.2.4 on 2023-08-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='date published')),
                ('date_end', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('disclaimer', models.CharField(default=None, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('business_emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_emissor', to='offert.business')),
                ('business_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_receptor', to='offert.business')),
            ],
        ),
        migrations.CreateModel(
            name='OffertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OffertDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('offert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offert.offert')),
            ],
        ),
        migrations.AddField(
            model_name='offert',
            name='offert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offert.offerttype'),
        ),
    ]
