# Generated by Django 4.2.4 on 2023-08-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offert',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
