# Generated by Django 4.2.4 on 2023-08-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offert', '0002_offert_discount_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='offert',
            name='discount_rate',
        ),
    ]
