# Generated by Django 4.2.4 on 2023-08-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offert', '0003_category_remove_offert_discount_rate_offert_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='offert',
            name='discount_rate',
        ),
    ]
