# Generated by Django 4.2.4 on 2023-08-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offert', '0003_offertcategory_remove_offert_discount_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
