# Generated by Django 4.2.4 on 2023-08-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offert', '0004_alter_offert_discount_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='offert',
            options={'ordering': ['date_start']},
        ),
    ]
