# Generated by Django 4.2.4 on 2023-08-23 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offert', '0004_alter_offert_discount_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offert',
            options={'ordering': ['date_start']},
        ),
        migrations.RemoveField(
            model_name='offert',
            name='business_emissor',
        ),
        migrations.AddField(
            model_name='offert',
            name='user_created',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
