# Generated by Django 4.2.4 on 2023-08-31 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offert', '0006_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offert',
            old_name='category',
            new_name='offert_category',
        ),
    ]
