version: "3"

services:
  app:
    build: .
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=db
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password
  

volumes:
  postgres_data: